"""
Shared fixtures for Ordering.API functional tests.
Manages the mock OIDC server, JWT token generation, and health checks.
"""
import os
import sys
import time
import uuid
import json
import subprocess
import signal
import requests
import pytest
import jwt
from datetime import datetime, timedelta, timezone

# Paths
TEST_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_DIR = os.path.dirname(os.path.dirname(os.path.dirname(TEST_DIR)))

# Configuration
ORDERING_API_PORT = os.environ.get("ORDERING_API_PORT", "5224")
MOCK_OIDC_PORT = os.environ.get("MOCK_OIDC_PORT", "5223")
BASE_URL = f"http://localhost:{ORDERING_API_PORT}"
MOCK_OIDC_URL = f"http://localhost:{MOCK_OIDC_PORT}"

# Test user identity (matches the functional test fixture from OrderingApiFixture)
TEST_USER_ID = "9e3163b9-1ae6-4652-9dc6-7898ab7b7a00"
TEST_USER_NAME = "ftrun_testuser"


def _load_private_key():
    """Load the RSA private key generated by the mock OIDC server."""
    key_file = os.path.join(TEST_DIR, "test_private_key.pem")
    if not os.path.exists(key_file):
        raise FileNotFoundError(
            f"Private key not found at {key_file}. "
            "Ensure the mock OIDC server has been started first."
        )
    with open(key_file, "r") as f:
        return f.read()


def _load_kid():
    """Load the key ID from the mock OIDC server."""
    kid_file = os.path.join(TEST_DIR, "test_kid.txt")
    if not os.path.exists(kid_file):
        return "test-key-1"
    with open(kid_file, "r") as f:
        return f.read().strip()


def generate_jwt_token(
    sub=TEST_USER_ID,
    name=TEST_USER_NAME,
    audience="orders",
    expires_in_minutes=60,
):
    """Generate a JWT token signed with the mock OIDC server's RSA key."""
    private_key_pem = _load_private_key()
    kid = _load_kid()

    now = datetime.now(timezone.utc)
    payload = {
        "sub": sub,
        "name": name,
        "unique_name": name,
        "iss": MOCK_OIDC_URL,
        "aud": audience,
        "iat": int(now.timestamp()),
        "nbf": int(now.timestamp()),
        "exp": int((now + timedelta(minutes=expires_in_minutes)).timestamp()),
        "scope": ["openid", "orders"],
    }
    headers = {"kid": kid, "alg": "RS256"}
    token = jwt.encode(payload, private_key_pem, algorithm="RS256", headers=headers)
    return token


@pytest.fixture(scope="session")
def auth_token():
    """Provide a valid JWT token for authenticated API requests."""
    return generate_jwt_token()


@pytest.fixture(scope="session")
def auth_headers(auth_token):
    """Provide HTTP headers with a valid JWT Bearer token."""
    return {"Authorization": f"Bearer {auth_token}"}


@pytest.fixture(autouse=True)
def health_check():
    """Verify the Ordering.API is reachable before running each test."""
    try:
        resp = requests.get(f"{BASE_URL}/alive", timeout=5)
        assert resp.status_code == 200, (
            f"Health check failed: /alive returned {resp.status_code}"
        )
    except requests.ConnectionError:
        pytest.fail(
            f"Ordering.API is not reachable at {BASE_URL}/alive. "
            "Ensure the app is running."
        )
